export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_CREATION_SUCCESSFUL = "USER_CREATION_SUCCESSFUL";
export const USER_CREATION_FAILED = "USER_CREATION_FAILED";
export const LOADING_STARTS = "LOADING_STARTS";
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";